In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,6],
    [2,8],
    [3,11],
    [3,10],
    [1,7]
])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [31]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [41]:
a_centered_sp = (a_centered[:, 0] @ a_centered[:, 1]) / (5-1)
a_centered_sp

2.0

In [40]:
np.cov(np.transpose(a))

array([[1. , 2. ],
       [2. , 4.3]])